version: '3'
services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "52001:80"
    environment:
      # - PASSWORD=${PASSWORD:-666666}
    restart: unless-stopped
